### ISSUE TITLE
Nicer printing of drivers

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/adbi#2]
Is it possible to inform about what kind of database this driver connects to? Currently seeing:

``` r
adbi::adbi("adbcsqlite")
#> <AdbiDriver>
```

<sup>Created on 2023-11-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by nbenn** [comment]
@krlmlr since v0.0.2 you get

```r
adbi::adbi("adbcsqlite")
#> <AdbiDriver>
#>   Type: <adbcsqlite_driver_sqlite>
```

I'm not sure there's much more (printing-relevant) information I can get out of the adbc driver object other than the class. Let me know if you feel differently.

**Comment by krlmlr** [comment]
Looks good enough, thanks!
