### ISSUE TITLE
nanoarrow_array_stream or nanoarrow_array?

### ISSUE THREAD

**Issue by eitsupi** [r-dbi/adbi#3]
The DBI package documentation and the DBItest shows that methods like `dbGetQueryArrow` return `nanoarrow_array_stream`, but the README of this repository seems to return `nanoarrow_array`.
Is this intentional?
https://github.com/r-dbi/adbi/blob/f56d677217b0bf1d5190a63e6ce28dc556bbc5ca/README.md?plain=1#L98-L99

**Comment by eitsupi** [comment]
Any update on this?

I tried to implement Arrow-related methods to `polarssql`, but the return value type is not listed in the documentation and I cannot see the implementation method.

**Comment by krlmlr** [comment]
The README now returns a nanoarrow array stream. The documentation at https://dbi.r-dbi.org/dev/reference/dbGetQueryArrow.html isn't very specific, intentionally. DBI's implementation for the fallback is accessible like this:

``` r
DBI:::dbGetQueryArrow_DBIConnection_character
#> function(conn, statement, ...) {
#>   rs <- dbSendQueryArrow(conn, statement, ...)
#>   on.exit(dbClearResult(rs))
#> 
#>   dbFetchArrow(rs, ...)
#> }
#> <environment: namespace:DBI>
DBI:::dbFetchArrow_DBIResultArrow
#> function(res, ...) {
#>   chunk <- dbFetchArrowChunk_DBIResultArrow(res)
#>   # Corner case: add empty chunk only for zero rows, for schema
#>   if (chunk$length == 0) {
#>     return(nanoarrow::basic_array_stream(
#>       list(),
#>       schema = nanoarrow::infer_nanoarrow_schema(chunk),
#>       validate = FALSE
#>     ))
#>   }
#> 
#>   out <- list(chunk)
#>   repeat {
#>     chunk <- dbFetchArrowChunk_DBIResultArrow(res)
#>     if (chunk$length == 0) {
#>       return(nanoarrow::basic_array_stream(
#>         out,
#>         schema = nanoarrow::infer_nanoarrow_schema(out[[1]]),
#>         validate = FALSE
#>       ))
#>     }
#>     out <- c(out, list(chunk))
#>   }
#> }
#> <environment: namespace:DBI>
```

<sup>Created on 2023-12-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by eitsupi** [comment]
I think this has been fixed, thanks!
